- name: Schedule inventory sync for the team
  hosts: localhost
  tasks:
  - name: create a schedule for the inventory source
    debug:
      # name: "Source Schedule"
      msg: "{{ lookup('awx.awx.schedule_rrule', 'none', start_date='2024-08-22 04:10:00', timezone='America/Denver') }}"
      # unified_job_template: "Demo Job Template"

