- name: Schedule inventory sync for the team
  hosts: localhost
  tasks:
  - name: Get our collection package
    controller_meta:
    register: controller_meta

  - name: Generate the name of our plugin
    set_fact:
      ruleset_plugin_name: "{{ controller_meta.prefix }}.schedule_rruleset"
      rule_plugin_name: "{{ controller_meta.prefix }}.schedule_rrule"


  - name: Call ruleset with no rules
    set_fact:
      complex_rule: "{{ lookup(ruleset_plugin_name | string, '2022-04-30 10:30:45') }}"
    ignore_errors: True
    register: results
